### ISSUE TITLE
Blank lines are not preserved by org.walkmod.javalang.ASTParser API

### ISSUE THREAD

**Issue by mohanasundar** [rpau/javalang#10]
Blank lines are not preserved by org.walkmod.javalang.ASTParser API.

Below steps gives the details of the issue.
1. Read the java file.
2. Get  CompilationUnit by calling CompilationUnit() method on ASTParser instance.
3. Invoke toString on CompilationUnit instance got in step 2.
4. Observe that the empty lines are removed.

Ex:
...
if(a){
....
}

if(b){
...
}
...

After parsing we get,

...
if(a){
....
}
if(b){
...
}
...

Observe the empty line between if is removed.

**Comment by rpau** [comment]
Hi, 

Thanks for the feedback. I will try fix it soon :) (probably this week)

**Comment by rpau** [comment]
Done :)  The version of the Maven artifact is 3.0.8
