### ISSUE TITLE
Parsing does not retain comments

### ISSUE THREAD

**Issue by prateekbaheti** [rpau/javalang#11]
Eg: For a Java file with contents:

``` java
public class StepImpl {   
    //comment
    public void stepWithComments() {
        // comment
        // comment
        /*
        comment
         */
    }
}
```

On parsing, the CompilationUnit does not retain comments:

``` java
public class StepImpl {   

    public void stepWithComments() {





    }
}
```

This is using version 4.1.0

**Comment by rpau** [comment]
Hi,

I have created a test  and the first "toString" call prints the comments, but not the second call. I have solved the issue and pushed my changes (version 4.2.0). Do you need that I deploy today it in maven?

Thanks for your feedback :)

**Comment by prateekbaheti** [comment]
Thanks for the quick response and fix.

The compilation unit toString() is printing the comments but when I visit the compilation unit with a VoidVisitorAdapter, on the visit method to the method, the MethodDeclaration does not have the comments on a toString(). 

My exact usage is [here](https://github.com/getgauge/gauge-java/blob/master/src/main/java/com/thoughtworks/gauge/refactor/RefactoringMethodVisitor.java#L52)

**Comment by rpau** [comment]
Ok, thank you. I can reproduce the problem now :)

I think that is not difficult to solve. I will try to solve it today. Anyway, give you feedback during this week.

**Comment by prateekbaheti** [comment]
Thanks. 
If you need my help on anything, do let me know. :)

**Comment by rpau** [comment]
Hi,

I have fixed this issue. However, playing with your example, if I apply the toString() method just in the MethodDeclaration node, I have seen that for example, block comments (/\* comment */) loose their indentation because the white characters are part of the comments. 

Example:
Original code: 

```
public class StepImpl {
    //comment
    public void stepWithComments() {
        // comment
        // comment
        /*
        comment
         */
    }
}
```

MethodDeclaration.toString() produces: 

```
public void stepWithComments() {
    // comment
    // comment
    /*
        comment
         */
}
```

Is it right for you? Otherwise, I can add an option to align the block comments :)

**Comment by rpau** [comment]
It has been deployed into maven with the 4.2.0 version.

**Comment by prateekbaheti** [comment]
Thanks for the update. Will try it out immediately.
